"""fix_missing_fields_promocodes_value_orders_pickup_or_delivery

Revision ID: 471a82df3ffb
Revises: 026c190f748b
Create Date: 2025-08-28 17:51:29.820821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471a82df3ffb'
down_revision: Union[str, Sequence[str], None] = '026c190f748b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_or_delivery', sa.String(length=16), nullable=False))
    op.drop_column('orders', 'fulfillment')
    op.add_column('promocodes', sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocodes', 'value')
    op.add_column('orders', sa.Column('fulfillment', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_column('orders', 'pickup_or_delivery')
    # ### end Alembic commands ###